"""Runtime context package.

This package was split out of the former single-module ``context.py``. The
public surface (and every previously module-level name, including
underscore-prefixed helpers) is re-exported here so that
``from genomi.runtime.context import X`` and
``import genomi.runtime.context as context; context.X`` keep working exactly as
before.
"""

from __future__ import annotations

from .normalize import (
    AGENT_SESSION_ENVS,
    AGI_ACCESS_KEY,
    CONTEXT_FILE_NAME,
    CONTEXT_VERSION,
    DEFAULT_CONTEXT_POLICY,
    DIGITIZATION_CONTRACT,
    GENOMI_CONTEXT_ENV,
    GENOMI_CONTEXT_POLICY_ENV,
    GENOMI_SESSION_ENV,
    JsonObject,
    REGISTRY_FILE_NAME,
    SESSIONS_DIR_NAME,
    _agent_session_id,
    _agi_map,
    _assert_unique_user_nickname,
    _attach_agi_to_user,
    _context_source_format,
    _default_user,
    _digest,
    _empty_agi_access_status,
    _empty_context,
    _empty_registry,
    _ensure_user_record,
    _find_user,
    _find_user_id_for_agi,
    _grant_agi_access,
    _mark_default_user,
    _normalize_agi_record,
    _normalize_context,
    _normalize_nickname,
    _normalize_registry,
    _normalize_user_record,
    _now,
    _outputs_from_result,
    _path_str,
    _redact_session_value,
    _removed_context_keys,
    _stable_session_id,
    _user_id_for_nickname,
    _user_map,
    _workspace_session_id,
)
from .storage import (
    context_path,
    context_policy,
    context_scope,
    get_response_profile_id,
    load_context,
    load_registry,
    registry_path,
    save_context,
    save_registry,
    set_response_profile_id,
)
from .agi import (
    _active_genome_index_state,
    _active_user,
    _auto_selected_run,
    _default_selected_agi,
    _find_agi,
    _is_digitized_run,
    _resolve_access_target,
    _selection_source,
    active_accessible_run,
    active_run,
    agi_access_approved,
    agi_access_status,
    approve_agi_access,
    clear_active_genome_index,
    describe_context,
    describe_run,
    describe_user,
    find_agi,
    infer_run,
    infer_source_run,
    list_agis,
    revoke_agi_access,
    save_agi_to_registry,
    save_run_to_registry,
    set_active_agi_id,
    set_active_genome_index,
    set_active_paths,
    set_active_source,
)
from .users import (
    assign_user_genome,
    clear_default_user,
    list_users,
    rename_user,
    select_user,
    set_default_user,
)

__all__ = [
    "AGENT_SESSION_ENVS",
    "AGI_ACCESS_KEY",
    "CONTEXT_FILE_NAME",
    "CONTEXT_VERSION",
    "DEFAULT_CONTEXT_POLICY",
    "DIGITIZATION_CONTRACT",
    "GENOMI_CONTEXT_ENV",
    "GENOMI_CONTEXT_POLICY_ENV",
    "GENOMI_SESSION_ENV",
    "JsonObject",
    "REGISTRY_FILE_NAME",
    "SESSIONS_DIR_NAME",
    "active_accessible_run",
    "active_run",
    "agi_access_approved",
    "agi_access_status",
    "approve_agi_access",
    "assign_user_genome",
    "clear_active_genome_index",
    "clear_default_user",
    "context_path",
    "context_policy",
    "context_scope",
    "describe_context",
    "describe_run",
    "describe_user",
    "find_agi",
    "get_response_profile_id",
    "infer_run",
    "infer_source_run",
    "list_agis",
    "list_users",
    "load_context",
    "load_registry",
    "registry_path",
    "rename_user",
    "revoke_agi_access",
    "save_agi_to_registry",
    "save_context",
    "save_registry",
    "save_run_to_registry",
    "select_user",
    "set_active_agi_id",
    "set_active_genome_index",
    "set_active_paths",
    "set_active_source",
    "set_default_user",
    "set_response_profile_id",
]
