from __future__ import annotations

import bz2
import gzip
import io
import struct
import tarfile
import tempfile
import unittest
import zipfile
from pathlib import Path

from genomi.active_genome_index.source_intake import detect_source

_ANCESTRY_TXT = (
    "#AncestryDNA raw data download\n"
    "#Genetic data is provided using human reference build 37.1 coordinates.\n"
    "rsid\tchromosome\tposition\tallele1\tallele2\n"
    "rs3131972\t1\t752721\tG\tG\n"
)
_23ANDME_TXT = (
    "# This data file generated by 23andMe at: Tue Jan 01 2019\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
    "rs3131972\t1\t752721\tGG\n"
)
_GVCF_TXT = (
    "##fileformat=VCFv4.2\n"
    '##ALT=<ID=NON_REF,Description="Represents any possible alternative allele">\n'
    "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
    "1\t100\t.\tA\t<NON_REF>\t.\tPASS\tEND=150\tGT\t0/0\n"
)
_PLAIN_VCF_TXT = (
    "##fileformat=VCFv4.2\n"
    "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
    "1\t100\trs1\tA\tG\t50\tPASS\t.\tGT\t0/1\n"
)
_FASTQ_TXT = "@READ1\nACGTACGT\n+\nFFFFFFFF\n"


class CompressionContentTests(unittest.TestCase):
    """Compression is peeled by magic bytes, not by the file extension."""

    def test_extensionless_gzip_array_is_detected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            # No `.gz` suffix at all — only the gzip magic identifies it.
            path = Path(tmp) / "downloaded_blob"
            path.write_bytes(gzip.compress(_ANCESTRY_TXT.encode()))
            detection = detect_source(path)
            self.assertEqual(detection.source_format, "ancestrydna")
            self.assertEqual(detection.reference_build, "GRCh37")

    def test_bzip2_array_is_detected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.txt.bz2"
            path.write_bytes(bz2.compress(_23ANDME_TXT.encode()))
            self.assertEqual(detect_source(path).source_format, "23andme")

    def test_gvcf_content_wins_over_plain_vcf_name(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            # Named `.vcf.gz` like a plain WGS callset, but the content is gVCF.
            path = Path(tmp) / "wgs.vcf.gz"
            path.write_bytes(gzip.compress(_GVCF_TXT.encode()))
            self.assertEqual(detect_source(path).source_format, "gvcf")

    def test_plain_vcf_without_extension(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "callset"
            path.write_text(_PLAIN_VCF_TXT)
            self.assertEqual(detect_source(path).source_format, "vcf")


class GvcfDiscriminationTests(unittest.TestCase):
    """``END=`` and a ``##ALT=<ID=NON_REF>`` header do not make a gVCF.

    Regression for real PGP Dante exports: CNV (`<DEL>`/`<DUP>`), SV (`<ITX>`),
    and genotype-array-derived VCFs all use ``END=``, and DRAGEN declares
    ``NON_REF`` in the header of plain SV callsets. Only a reference-confidence
    data record (`<NON_REF>`/`<*>`) marks a gVCF.
    """

    def _detect(self, body: str) -> str:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "callset.vcf"
            path.write_text(body)
            return detect_source(path).source_format

    def test_cnv_vcf_with_end_is_plain_vcf(self) -> None:
        body = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS\n"
            "1\t2157780\t.\tN\t<DEL>\t9\tPASS\tSVTYPE=CNV;END=2160792\tGT\t0/1\n"
        )
        self.assertEqual(self._detect(body), "vcf")

    def test_sv_vcf_with_header_non_ref_declaration_is_plain_vcf(self) -> None:
        body = (
            "##fileformat=VCFv4.2\n"
            '##ALT=<ID=NON_REF,Description="any possible alt">\n'
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS\n"
            "chr1\t536036\t.\tC\t<ITX>\t.\tPASS\tSVTYPE=ITX;END=536156\tGT\t0/1\n"
        )
        self.assertEqual(self._detect(body), "vcf")

    def test_genotype_array_vcf_with_end_blocks_is_plain_vcf(self) -> None:
        body = (
            "##fileformat=VCFv4.1\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS\n"
            "1\t768448\trs12562034\tG\t.\t.\t.\tEND=768448\tGT\t0/0\n"
        )
        self.assertEqual(self._detect(body), "vcf")

    def test_reference_confidence_record_is_gvcf(self) -> None:
        body = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS\n"
            "1\t100\t.\tA\t<NON_REF>\t.\tPASS\tEND=150\tGT\t0/0\n"
        )
        self.assertEqual(self._detect(body), "gvcf")

    def test_gvcfblock_header_is_gvcf(self) -> None:
        body = (
            "##fileformat=VCFv4.2\n"
            "##GVCFBlock0-1=minGQ=0(inclusive),maxGQ=1(exclusive)\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS\n"
            "1\t100\t.\tA\tG\t.\tPASS\t.\tGT\t0/1\n"
        )
        self.assertEqual(self._detect(body), "gvcf")


class ArchiveContentTests(unittest.TestCase):
    """zip and tar archives are peeled and the genomic member is selected."""

    def test_tar_gz_array_member_is_selected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "bundle.tar.gz"
            with tarfile.open(path, "w:gz") as archive:
                data = _ANCESTRY_TXT.encode()
                info = tarfile.TarInfo("AncestryDNA.txt")
                info.size = len(data)
                archive.addfile(info, io.BytesIO(data))
            detection = detect_source(path)
            self.assertEqual(detection.source_format, "ancestrydna")
            self.assertEqual(detection.member_name, "AncestryDNA.txt")

    def test_zip_skips_junk_and_selects_genotype_member(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "export.zip"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("README.pdf", "not genomic")
                archive.writestr("__MACOSX/._AncestryDNA.txt", "resource fork")
                archive.writestr("AncestryDNA.txt", _ANCESTRY_TXT)
            detection = detect_source(path)
            self.assertEqual(detection.source_format, "ancestrydna")
            self.assertEqual(detection.member_name, "AncestryDNA.txt")

    def test_tar_member_can_itself_be_gzipped(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "nested.tar"
            with tarfile.open(path, "w") as archive:
                data = gzip.compress(_23ANDME_TXT.encode())
                info = tarfile.TarInfo("genome.txt.gz")
                info.size = len(data)
                archive.addfile(info, io.BytesIO(data))
            self.assertEqual(detect_source(path).source_format, "23andme")

    def test_fastq_archive_requires_paired_member(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "reads.zip"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("reads/sample_R1_001.fastq.gz", gzip.compress(_FASTQ_TXT.encode()))

            with self.assertRaises(ValueError) as raised:
                detect_source(path)
            self.assertIn("R2 member", str(raised.exception))

    def test_fastq_archive_selects_r1_member_for_pair(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "reads.zip"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("reads/sample_R2_001.fastq.gz", gzip.compress(_FASTQ_TXT.encode()))
                archive.writestr("reads/sample_R1_001.fastq.gz", gzip.compress(_FASTQ_TXT.encode()))

            detection = detect_source(path)
            self.assertEqual(detection.source_format, "fastq")
            self.assertEqual(detection.member_name, "reads/sample_R1_001.fastq.gz")

    def test_fastq_archive_skips_sample_sheet_sidecar(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "reads-with-sidecar.zip"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("SampleSheet.csv", "Sample_ID,Sample_Name\n1,sidecar\n")
                archive.writestr("reads/sample_R1_001.fastq.gz", gzip.compress(_FASTQ_TXT.encode()))
                archive.writestr("reads/sample_R2_001.fastq.gz", gzip.compress(_FASTQ_TXT.encode()))

            detection = detect_source(path)
            self.assertEqual(detection.source_format, "fastq")
            self.assertEqual(detection.member_name, "reads/sample_R1_001.fastq.gz")


class BinaryFormatTests(unittest.TestCase):
    """Alignment formats are recognized by decompressed/raw magic bytes."""

    def test_bam_detected_by_content_despite_extension(self) -> None:
        import pysam

        with tempfile.TemporaryDirectory() as tmp:
            # Deliberately misleading extension; the BGZF->BAM\1 magic decides.
            path = Path(tmp) / "alignment.dat"
            header = {"HD": {"VN": "1.6"}, "SQ": [{"SN": "1", "LN": 1000}]}
            with pysam.AlignmentFile(str(path), "wb", header=header):
                pass
            self.assertEqual(detect_source(path).source_format, "bam")

    def test_zipped_bam_member_is_detected_after_bgzf_decompression(self) -> None:
        import pysam

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            bam = root / "sample.bam"
            header = {"HD": {"VN": "1.6"}, "SQ": [{"SN": "1", "LN": 1000}]}
            with pysam.AlignmentFile(str(bam), "wb", header=header):
                pass
            archive_path = root / "alignment.zip"
            with zipfile.ZipFile(archive_path, "w") as archive:
                archive.write(bam, "reads/sample.bam")

            detection = detect_source(archive_path)
            self.assertEqual(detection.source_format, "bam")
            self.assertEqual(detection.member_name, "reads/sample.bam")

    def test_cram_magic_raises_clear_error(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "reads.bin"
            path.write_bytes(b"CRAM" + struct.pack("BB", 3, 0) + b"\x00" * 32)
            with self.assertRaises(ValueError) as raised:
                detect_source(path)
            self.assertIn("CRAM", str(raised.exception))


class UnknownContentTests(unittest.TestCase):
    def test_unrecognized_content_raises(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "mystery.dat"
            path.write_text("just some prose that is not a genome file at all\n")
            with self.assertRaises(ValueError):
                detect_source(path)


if __name__ == "__main__":
    unittest.main()
