from __future__ import annotations

import os
import tempfile
from pathlib import Path
from unittest import mock

from genomi.operations import call_operation
from genomi.runtime import context as runtime_context

from tests.support.runtime.genomi import GenomiRuntimeTestCase


def _write_vcf(path: Path) -> None:
    path.write_text(
        "##fileformat=VCFv4.2\n"
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsample\n"
        "1\t100\trs1\tA\tG\t50\tPASS\t.\tGT\t0/1\n",
        encoding="utf-8",
    )


def _write_23andme(path: Path) -> None:
    path.write_text(
        "# This data file is generated by 23andMe.\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t100\tAA\n",
        encoding="utf-8",
    )


class ParseSourcePathExpansionTests(GenomiRuntimeTestCase):
    def test_parse_source_expands_home_directory(self) -> None:
        with tempfile.TemporaryDirectory() as home:
            source = Path(home) / "genome.vcf"
            _write_vcf(source)

            with mock.patch.dict(os.environ, {"HOME": home}):
                parsed = call_operation("genomi.parse_source", {"source": "~/genome.vcf"})

        self.assertEqual(parsed["status"], "completed")
        self.assertEqual(parsed["source_format"], "vcf")

    def test_parse_source_expands_environment_variables(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source_dir = Path(tmp) / "sources"
            source_dir.mkdir()
            source = source_dir / "genome.vcf"
            _write_vcf(source)

            with mock.patch.dict(os.environ, {"GENOMI_TEST_SOURCE_DIR": str(source_dir)}):
                parsed = call_operation(
                    "genomi.parse_source",
                    {"source": "$GENOMI_TEST_SOURCE_DIR/genome.vcf"},
                )

        self.assertEqual(parsed["status"], "completed")
        self.assertEqual(parsed["source_format"], "vcf")

    def test_assign_user_by_source_uses_existing_digitized_array_agi(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            raw = Path(tmp) / "genome.txt"
            _write_23andme(raw)

            parsed = call_operation("genomi.parse_source", {"source": str(raw)})
            parsed_agi_id = parsed["active_genome_index"]["agi_id"]
            profile_action = next(
                item for item in parsed["next_actions"] if item.get("action") == "ask_user"
            )
            assigned = call_operation(
                "active_genome_index.assign_user_genome",
                {"nickname": "Sample user", "source": str(raw)},
            )

        self.assertTrue(parsed_agi_id.startswith("23andme-sha256-"))
        self.assertEqual(profile_action["operation"], "active_genome_index.assign_user_genome")
        self.assertEqual(profile_action["params"]["nickname"], "<profile nickname>")
        self.assertEqual(assigned["user"]["active_agi_id"], parsed_agi_id)
        self.assertTrue(assigned["user"]["active_genome_index"]["digitized"])
        self.assertEqual(assigned["context"]["active_agi_id"], parsed_agi_id)

    def test_decode_uses_digitized_agi_after_profile_assignment_by_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            raw = Path(tmp) / "genome.txt"
            _write_23andme(raw)

            call_operation("genomi.parse_source", {"source": str(raw)})
            call_operation(
                "active_genome_index.assign_user_genome",
                {"nickname": "Sample user", "source": str(raw)},
            )
            built = call_operation("decode.build_dashboard_evidence", {"panels": ["overview"]})

        self.assertEqual(built["status"], "completed")
        self.assertEqual(built["panels_ready"], ["overview"])
        overview = built["render_params"]["evidence"]["overview"]["active_genome_index"]
        self.assertEqual(overview["active_genome_index_readiness"]["status"], "completed")
        self.assertEqual(overview["metadata"]["source_format"], "23andme")
        self.assertEqual(overview["stats"]["array_call_records"], 1)

    def test_reparse_persists_current_agi_record_shape(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            raw = Path(tmp) / "genome.txt"
            _write_23andme(raw)

            parsed = call_operation("genomi.parse_source", {"source": str(raw)})
            agi_id = parsed["active_genome_index"]["agi_id"]
            context = call_operation("genomi.describe_context")
            context_record = context["session_agis"][0]
            context_record["debug_note"] = "temporary"

            current_context = runtime_context.load_context()
            current_context["agis"][agi_id] = context_record
            runtime_context.save_context(current_context)
            reparsed = call_operation("genomi.parse_source", {"source": str(raw), "force": True})

        self.assertEqual(reparsed["active_genome_index"]["agi_id"], agi_id)
        self.assertEqual(reparsed["active_genome_index"]["agi_source_format"], "23andme")
        self.assertEqual(
            set(runtime_context.load_context()["agis"][agi_id]),
            {
                "agi_comparable_variant_export",
                "agi_id",
                "agi_intake_source_path",
                "agi_path",
                "agi_source_format",
                "agi_source_kind",
                "agi_source_member",
                "agi_source_provider",
                "candidate_inventory",
                "created_at",
                "evidence_db",
                "evidence_dir",
                "genome_build",
                "genotype_reference_fasta",
                "matches",
                "outputs",
                "project_dir",
                "reference_dir",
                "reference_fasta",
                "sample_slug",
                "shared_evidence_db",
                "source_content_sha256",
                "status",
                "updated_at",
                "work_dir",
            },
        )

    def test_active_selection_uses_registry_record_for_active_agi_id(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            raw = Path(tmp) / "genome.txt"
            _write_23andme(raw)

            parsed = call_operation("genomi.parse_source", {"source": str(raw)})
            agi_id = parsed["active_genome_index"]["agi_id"]
            context = runtime_context.load_context()
            context["agis"][agi_id] = {
                "agi_id": agi_id,
                "sample_slug": agi_id,
                "status": "set",
            }
            runtime_context.save_context(context)
            selected = call_operation("genomi.describe_context")

        self.assertEqual(selected["active_genome_index"]["agi_id"], agi_id)
        self.assertTrue(selected["active_genome_index"]["digitized"])
        self.assertEqual(selected["active_genome_index"]["agi_source_format"], "23andme")
