from __future__ import annotations

import gzip
import json
import os
import tempfile
import zipfile
from pathlib import Path

from genomi.operations import call_operation
from genomi.operations.registry.errors import OperationError
from genomi.active_genome_index.active_genome_index import SCHEMA_VERSION, active_genome_index_readiness
from genomi.runtime.sqlite_support import connect_sqlite

from tests.support.runtime.genomi import GenomiRuntimeTestCase


def _hidden_path_leaks(payload: object, *paths: Path) -> list[str]:
    hidden = {
        value
        for path in paths
        for value in (str(path), str(path.expanduser().resolve(strict=False)))
    }
    leaks: list[str] = []

    def visit(value: object, location: str) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                visit(item, f"{location}.{key}")
            return
        if isinstance(value, list):
            for index, item in enumerate(value):
                visit(item, f"{location}[{index}]")
            return
        if isinstance(value, str) and any(path in value for path in hidden):
            leaks.append(location)

    visit(payload, "$")
    return leaks


class GenomiRuntimeArrayIntakeTests(GenomiRuntimeTestCase):
    def test_active_genome_index_parse_accepts_direct_genome_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("contract.genome")
                raw.write_text(
                    "# raw genotype export\n"
                    "# rsid\tchromosome\tposition\tgenotype\n"
                    "rs123\t1\t100\tAG\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})

                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "genome")
                self.assertEqual(parsed["active_genome_index"]["agi_source_format"], "genome")
                readiness = active_genome_index_readiness(parsed["outputs"]["agi_path"])
                self.assertEqual(readiness["status"], "completed")
                self.assertTrue(readiness["complete"])

                lookup = call_operation("variant.resolve", {"rsid": "rs123"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                self.assertEqual(lookup["sample_context"]["matches"][0]["agi_source_format"], "genome")
                self.assertEqual(lookup["sample_context"]["matches"][0]["observed_alleles"], ["A", "G"])
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_23andme_raw_text(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("genome_PGP_PUBLIC_v5_Full_20230726173828.txt")
                raw.write_text(
                    "# This data file generated by 23andMe at: Wed Jul 26 17:38:28 2023\n"
                    "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n"
                    "# rsid\tchromosome\tposition\tgenotype\n"
                    "rs123\t1\t100\tAG\n"
                    "rs999\t2\t200\t--\n"
                    "rsDot\t3\t300\t.\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "23andme")
                self.assertIn("active_genome_index", parsed)
                readiness = active_genome_index_readiness(parsed["outputs"]["agi_path"])
                self.assertTrue(readiness["complete"])
                self.assertEqual(readiness["status"], "completed")
                self.assertEqual(readiness["missing_objects"], [])
                stats = parsed["steps"][0]["result"]["stats"]
                self.assertEqual(stats["variant_records"], 0)
                self.assertEqual(stats["array_call_records"], 1)
                self.assertEqual(stats["reference_records"], 0)
                self.assertEqual(stats["array_no_call_records"], 2)
                self.assertEqual(_hidden_path_leaks(parsed, raw), [])

                agi_path = Path(parsed["outputs"]["agi_path"])
                with connect_sqlite(agi_path) as connection:
                    no_call = connection.execute("select * from records where rsid = 'rs999'").fetchone()
                    dot_no_call = connection.execute("select * from records where rsid = 'rsDot'").fetchone()
                self.assertIsNotNone(no_call)
                self.assertEqual(no_call["filter"], "NO_CALL")
                self.assertEqual(no_call["format"], "GT_ARRAY")
                self.assertEqual(no_call["is_variant"], 0)
                self.assertEqual(no_call["record_kind"], "array_no_call")
                self.assertIsNone(no_call["observed_alleles"])
                self.assertEqual(no_call["info"], ".")
                self.assertIsNotNone(dot_no_call)
                self.assertEqual(dot_no_call["filter"], "NO_CALL")
                self.assertEqual(dot_no_call["format"], "GT_ARRAY")
                self.assertEqual(dot_no_call["is_variant"], 0)
                self.assertEqual(dot_no_call["record_kind"], "array_no_call")
                self.assertIsNone(dot_no_call["observed_alleles"])
                self.assertEqual(dot_no_call["info"], ".")

                current = call_operation("genomi.describe_context")
                self.assertTrue(current["has_active_genome_index"])
                self.assertEqual(current["active_genome_index"]["agi_source_format"], "23andme")
                current_readiness = current["active_genome_index"]["active_genome_index_readiness"]
                self.assertTrue(current_readiness["complete"])
                self.assertEqual(current_readiness["status"], "completed")
                self.assertEqual(_hidden_path_leaks(current, raw), [])

                lookup = call_operation("variant.resolve", {"rsid": "rs123"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                match = lookup["sample_context"]["matches"][0]
                self.assertEqual(match["genotype"], "AG")
                self.assertEqual(match["agi_source_format"], "23andme")
                self.assertEqual(match["record_kind"], "array_call")
                self.assertEqual(match["observed_alleles"], ["A", "G"])
                self.assertEqual(_hidden_path_leaks(lookup, raw), [])

                no_call_lookup = call_operation("variant.resolve", {"rsid": "rs999", "include_fail": True})
                self.assertEqual(no_call_lookup["sample_context"]["count"], 1)
                no_call_match = no_call_lookup["sample_context"]["matches"][0]
                self.assertEqual(no_call_match["filter"], "NO_CALL")
                self.assertEqual(no_call_match["record_kind"], "array_no_call")
                self.assertEqual(no_call_match["observed_alleles"], [])

                qc = call_operation("active_genome_index.classify_callset_qc", {"genome_build": "GRCh37", "scan_records": 10})
                self.assertEqual(qc["status"], "completed", qc)
                self.assertEqual(qc["input_type"], "array_or_genotyping_callset")
                self.assertFalse(qc["has_reference_blocks"])
                self.assertFalse(qc["absence_claims_allowed_by_default"])
                self.assertEqual(qc["summary"]["reference_records"], 0)
                self.assertEqual(qc["summary"]["no_call_records"], 2)
                self.assertEqual(qc["summary"]["array_no_call_records"], 2)

                callability = call_operation(
                    "active_genome_index.classify_region_callability",
                    {"region": "2:200-200", "genome_build": "GRCh37"},
                )
                self.assertEqual(callability["status"], "completed", callability)
                self.assertEqual(callability["callability_status"], "unknown_no_reference_blocks")
                self.assertFalse(callability["can_support_negative_or_reference_claim"])
                self.assertEqual(callability["matched_records"][0]["record_kind"], "array_no_call")
            finally:
                os.chdir(previous)

    def test_23andme_parse_rebuilds_incomplete_array_index(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("genome_PGP_PUBLIC_v5_Full_20230726173828.txt")
                raw.write_text(
                    "# This data file generated by 23andMe at: Wed Jul 26 17:38:28 2023\n"
                    "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n"
                    "# rsid\tchromosome\tposition\tgenotype\n"
                    "rs123\t1\t100\tAG\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                agi_path = Path(parsed["outputs"]["agi_path"])
                with connect_sqlite(agi_path) as connection:
                    connection.execute("drop table source_header_lines")
                    connection.execute("delete from metadata where key in ('active_genome_index_build_status', 'active_genome_index_complete')")
                    connection.commit()
                broken = active_genome_index_readiness(agi_path)
                self.assertFalse(broken["complete"])
                self.assertIn("table:source_header_lines", broken["missing_objects"])

                rebuilt = call_operation("genomi.parse_source", {"source": str(raw)})
                step_result = rebuilt["steps"][0]["result"]
                self.assertEqual(step_result["status"], "completed")
                repaired = active_genome_index_readiness(agi_path)
                self.assertTrue(repaired["complete"])
                self.assertEqual(repaired["missing_objects"], [])
            finally:
                os.chdir(previous)

    def test_consumer_array_parse_refuses_too_new_active_genome_index_schema(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("genome_schema_future.txt")
                raw.write_text(
                    "# This data file is generated by 23andMe.\n"
                    "# rsid\tchromosome\tposition\tgenotype\n"
                    "rs123\t1\t100\tAG\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                agi_path = Path(parsed["outputs"]["agi_path"])
                with connect_sqlite(agi_path) as connection:
                    connection.execute(
                        "update metadata set value = ? where key = 'schema_version'",
                        (json.dumps(SCHEMA_VERSION + 1),),
                    )
                    connection.commit()

                with self.assertRaises(OperationError) as raised:
                    call_operation("genomi.parse_source", {"source": str(raw)})

                self.assertEqual(raised.exception.code, "active_genome_index_schema_too_new")
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_ancestrydna_raw_text(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("AncestryDNA.txt")
                raw.write_text(
                    "#AncestryDNA raw data download\n"
                    "#This file was generated by AncestryDNA at: 11/18/2024 17:49:40 UTC\n"
                    "#Data was collected using AncestryDNA array version: V2.0\n"
                    "#Genetic data is reported using human reference build 37.1 coordinates.\n"
                    "rsid\tchromosome\tposition\tallele1\tallele2\n"
                    "rs3131972\t1\t752721\tA\tG\n"
                    "rs999\t2\t200\t0\t0\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "ancestrydna")
                self.assertEqual(parsed["source_kind"], "consumer_genotype_array")
                self.assertIn("active_genome_index", parsed)
                self.assertEqual(_hidden_path_leaks(parsed, raw), [])

                current = call_operation("genomi.describe_context")
                self.assertTrue(current["has_active_genome_index"])
                self.assertEqual(current["active_genome_index"]["agi_source_format"], "ancestrydna")
                self.assertEqual(_hidden_path_leaks(current, raw), [])

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                match = lookup["sample_context"]["matches"][0]
                self.assertEqual(match["genotype"], "AG")
                self.assertEqual(match["agi_source_format"], "ancestrydna")
                self.assertEqual(match["record_kind"], "array_call")
                self.assertEqual(match["observed_alleles"], ["A", "G"])
                self.assertEqual(_hidden_path_leaks(lookup, raw), [])
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_ancestrydna_zip(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                archive_path = Path("dna-data-2023-04-26.zip")
                content = (
                    "#AncestryDNA raw data download\n"
                    "#This file was generated by AncestryDNA at: 04/26/2023 04:30:29 UTC\n"
                    "#Data is formatted using AncestryDNA converter version: V1.0\n"
                    "#Genetic data is provided using human reference build 37.1 coordinates.\n"
                    "rsid\tchromosome\tposition\tallele1\tallele2\n"
                    "rs3131972\t1\t752721\tG\tG\n"
                )
                with zipfile.ZipFile(archive_path, "w") as archive:
                    archive.writestr("AncestryDNA.txt", content)

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(archive_path)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "ancestrydna")
                self.assertEqual(parsed["source_member"], "AncestryDNA.txt")
                self.assertEqual(_hidden_path_leaks(parsed, archive_path), [])

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                self.assertEqual(lookup["sample_context"]["matches"][0]["genotype"], "GG")
                self.assertEqual(lookup["sample_context"]["matches"][0]["agi_source_format"], "ancestrydna")
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_myheritage_raw_csv(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("MyHeritage_raw_dna_data.csv")
                raw.write_text(
                    "# MyHeritage DNA raw data.\n"
                    "# This file was generated on 2018-01-01 02:34:37 \n"
                    "# Reported with respect to human reference build 37.\n"
                    "RSID,CHROMOSOME,POSITION,RESULT\n"
                    '"rs3131972","1","752721","GG"\n'
                    '"rs999","2","200","--"\n',
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "myheritage")
                self.assertEqual(parsed["source_kind"], "consumer_genotype_array")
                self.assertEqual(parsed["provider"], "myheritage")

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                match = lookup["sample_context"]["matches"][0]
                self.assertEqual(match["genotype"], "GG")
                self.assertEqual(match["agi_source_format"], "myheritage")
                self.assertEqual(match["record_kind"], "array_call")
                self.assertEqual(match["observed_alleles"], ["G", "G"])
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_myheritage_zip(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                archive_path = Path("MyHeritage_raw_dna_data.zip")
                content = (
                    "# MyHeritage DNA raw data.\n"
                    "# Reported with respect to human reference build 37.\n"
                    "RSID,CHROMOSOME,POSITION,RESULT\n"
                    '"rs3131972","1","752721","GG"\n'
                )
                with zipfile.ZipFile(archive_path, "w") as archive:
                    archive.writestr("MyHeritage_raw_dna_data.csv", content)

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(archive_path)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "myheritage")
                self.assertEqual(parsed["source_member"], "MyHeritage_raw_dna_data.csv")

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["matches"][0]["genotype"], "GG")
                self.assertEqual(lookup["sample_context"]["matches"][0]["agi_source_format"], "myheritage")
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_ftdna_raw_csv(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("691234_Autosomal_o37_Results_20190228.csv")
                raw.write_text(
                    "RSID,CHROMOSOME,POSITION,RESULT\n"
                    '"rs3131972","1","752721","GG"\n'
                    '"rs999","2","200","--"\n',
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "ftdna")
                self.assertEqual(parsed["source_kind"], "consumer_genotype_array")
                self.assertEqual(parsed["provider"], "ftdna")

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                match = lookup["sample_context"]["matches"][0]
                self.assertEqual(match["genotype"], "GG")
                self.assertEqual(match["agi_source_format"], "ftdna")
                self.assertEqual(match["record_kind"], "array_call")
                self.assertEqual(match["observed_alleles"], ["G", "G"])
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_ftdna_gzip(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                archive_path = Path("691234_Autosomal_o37_Results_20190228.csv.gz")
                content = (
                    "RSID,CHROMOSOME,POSITION,RESULT\n"
                    '"rs3131972","1","752721","GG"\n'
                ).encode("utf-8")
                with gzip.open(archive_path, "wb") as handle:
                    handle.write(content)

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(archive_path)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "ftdna")

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["matches"][0]["genotype"], "GG")
            finally:
                os.chdir(previous)

    def test_active_genome_index_parse_accepts_livingdna_raw_text(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            previous = os.getcwd()
            os.chdir(tmp)
            try:
                raw = Path("living-dna-PGP_PUBLIC-autosomal.txt")
                raw.write_text(
                    "# Living DNA customer genotype data download file version: 1.0.2\n"
                    "# Human Genome Reference Build 37 (GRCh37.p13).\n"
                    "#\n"
                    "# rsid\tchromosome\tposition\tgenotype\n"
                    "rs3131972\t1\t752721\tGG\n"
                    "rs999\t2\t200\t--\n",
                    encoding="utf-8",
                )

                self.approve_access()
                parsed = call_operation("genomi.parse_source", {"source": str(raw)})
                self.assertEqual(parsed["status"], "completed")
                self.assertEqual(parsed["source_format"], "livingdna")
                self.assertEqual(parsed["source_kind"], "consumer_genotype_array")
                self.assertEqual(parsed["provider"], "livingdna")

                lookup = call_operation("variant.resolve", {"rsid": "rs3131972"})
                self.assertEqual(lookup["sample_context"]["count"], 1)
                match = lookup["sample_context"]["matches"][0]
                self.assertEqual(match["genotype"], "GG")
                self.assertEqual(match["agi_source_format"], "livingdna")
                self.assertEqual(match["record_kind"], "array_call")
                self.assertEqual(match["observed_alleles"], ["G", "G"])
            finally:
                os.chdir(previous)
