"""Drug-target gene prioritization and disease clinical drug-target retrieval (facade package)."""

from __future__ import annotations

from ._base import (
    ASSOCIATION_ONLY_SOURCE_TOKENS,
    CLINICAL_STAGE_RANK,
    DISEASE_DRUG_TARGET_RETRIEVAL_SCHEMA_VERSION,
    DRUG_TARGET_PRIORITIZATION_SCHEMA_VERSION,
    DRUG_TARGET_SOURCE_IDS,
    DRUG_TARGET_SOURCE_TOKENS,
    LOW_INFORMATION_TOKENS,
    OPENTARGETS_DISEASE_SEARCH_LIMIT,
    OPENTARGETS_GRAPHQL_API_URL,
    TOKEN_RE,
    _any_field_matches,
    _as_list,
    _canonical_phrase,
    _clean_text,
    _clinical_stage_rank,
    _context_token_overlap,
    _dedupe,
    _dedupe_dicts,
    _dedupe_records,
    _fetch_opentargets_graphql,
    _field_matches,
    _first_semantic_text,
    _meaningful_tokens,
    _normalize_gene,
    _normalize_genes,
    _normalize_terms,
    _record_digest,
    _tokens,
    _value_supported_by_text,
)
from .disease_targets import (
    _disease_drug_target_response,
    _disease_drug_target_semantic_usage,
    _first_disease_hits,
    _gene_membership_rows,
    _group_disease_drug_targets,
    _highest_stage,
    _normalize_retrieval_mode,
    _opentargets_disease_drug_target_records,
    _opentargets_disease_search,
    _record_context_values,
    _reference_urls,
    _representative_clinical_report,
    _semantic_disease_queries,
    _semantic_drug_target_fields,
    retrieve_disease_clinical_drug_targets,
)
from .comparison import (
    _candidate_row,
    _counter_evidence,
    _decision_policy,
    _derive_gene_candidates,
    _direct_relationship,
    _evidence_summary,
    _gene_mentioned,
    _gene_verified,
    _merge_verified_fields,
    _negative_record,
    _next_actions,
    _normalize_source_record,
    _prepare_source_records,
    _query_context,
    _query_context_support,
    _rank_candidates,
    _record_templates,
    _record_text,
    _score_record,
    _source_family,
    _source_review_plan,
    _status,
    _stored_records,
    _stored_research_to_source_record,
    _stored_search_queries,
    _summary,
    _valid_support_spans,
    _verification_limitations,
    _verification_status,
    _verified_field_text,
    _verified_fields,
    _verified_fields_from_spans,
    _warnings,
    _why_not_selected,
    compare_target_gene_evidence,
)

__all__ = [
    "DISEASE_DRUG_TARGET_RETRIEVAL_SCHEMA_VERSION",
    "DRUG_TARGET_PRIORITIZATION_SCHEMA_VERSION",
    "OPENTARGETS_GRAPHQL_API_URL",
    "OPENTARGETS_DISEASE_SEARCH_LIMIT",
    "compare_target_gene_evidence",
    "retrieve_disease_clinical_drug_targets",
]
