"""Journal capability facade.

This package preserves the public surface of the former ``journal.py`` module.
All names previously importable from ``genomi.capabilities.journal.journal`` are
re-exported here so existing import paths continue to work unchanged.
"""

from __future__ import annotations

from ._constants import (
    AMENDMENT_TYPES,
    CLAIM_LIKE_ENTRY_TYPES,
    DECISION_STATUSES,
    ENTRY_TYPES,
    JOURNAL_DB_NAME,
    JOURNAL_SCHEMA,
    JOURNALS_DIR_NAME,
    MEMORY_ARTIFACT_SCHEMA,
    PRIVATE_OPERATION_PREFIXES,
    PRIVATE_OPERATIONS,
    PRIVATE_PAYLOAD_KEYS,
    PRIVATE_SCOPE_MARKERS,
    JournalError,
    JsonObject,
)
from ._helpers import (
    _all_matching_entries,
    _assert_links_allowed,
    _compact_entry,
    _connect,
    _contains_private_marker,
    _digest,
    _drop_none,
    _ensure_notebook,
    _entry_matches,
    _hydrate_entry,
    _include_private_evidence,
    _init_schema,
    _insert_link,
    _is_private_evidence_link,
    _journal_retrieval_document,
    _json_dumps,
    _json_loads,
    _link_response,
    _locate_entry,
    _memory_type,
    _most_used_evidence_sources,
    _new_id,
    _normalize_decision_status,
    _normalize_link,
    _normalize_tags,
    _normalize_target,
    _notebook_for_entry,
    _now,
    _optional_text,
    _public_notebook,
    _required_text,
    _row_dict,
    _scope_id,
    _selected_scopes,
    _target_matches,
    _tokens,
    _validate_amendment_type,
    _validate_entry_type,
    _validate_scope,
    _workspace_scope_id,
    journal_db_path,
)
from ._operations import (
    _append_to_existing_entry,
    _semantic_journal_entries,
    append_entry,
    export_memory_artifact,
    journal_inventory,
    search_entries,
    summarize_notebook,
)

__all__ = [
    "AMENDMENT_TYPES",
    "CLAIM_LIKE_ENTRY_TYPES",
    "DECISION_STATUSES",
    "ENTRY_TYPES",
    "JOURNAL_DB_NAME",
    "JOURNAL_SCHEMA",
    "JOURNALS_DIR_NAME",
    "MEMORY_ARTIFACT_SCHEMA",
    "PRIVATE_OPERATION_PREFIXES",
    "PRIVATE_OPERATIONS",
    "PRIVATE_PAYLOAD_KEYS",
    "PRIVATE_SCOPE_MARKERS",
    "JournalError",
    "JsonObject",
    "append_entry",
    "export_memory_artifact",
    "journal_db_path",
    "journal_inventory",
    "search_entries",
    "summarize_notebook",
]
