"""Active Genome Index public hub.

The implementation lives in cohesive sibling modules (``_agi_schema``,
``_agi_readiness``, ``_agi_query``, ``_agi_build``); this module re-exports the
public and cross-referenced names so ``from genomi.active_genome_index.
active_genome_index import X`` keeps working unchanged.
"""

from __future__ import annotations

from ._agi_schema import (
    SCHEMA_VERSION as SCHEMA_VERSION,
    ACTIVE_GENOME_INDEX_BUILD_STATUS_IN_PROGRESS as ACTIVE_GENOME_INDEX_BUILD_STATUS_IN_PROGRESS,
    ACTIVE_GENOME_INDEX_BUILD_STATUS_COMPLETED as ACTIVE_GENOME_INDEX_BUILD_STATUS_COMPLETED,
    ACTIVE_GENOME_INDEX_BUILD_STATUS_VARIANTS_READY as ACTIVE_GENOME_INDEX_BUILD_STATUS_VARIANTS_READY,
    REQUIRED_QUERY_OBJECTS as REQUIRED_QUERY_OBJECTS,
    ActiveGenomeIndexStats as ActiveGenomeIndexStats,
    default_active_genome_index_path as default_active_genome_index_path,
    connect as connect,
    connect_existing as connect_existing,
    _active_genome_index_build_lock as _active_genome_index_build_lock,
    _is_plain_vcf as _is_plain_vcf,
    _byte_ranges as _byte_ranges,
    _shard_path as _shard_path,
    _multiprocessing_context as _multiprocessing_context,
    _reset_schema as _reset_schema,
    _create_query_indexes as _create_query_indexes,
    _insert_metadata as _insert_metadata,
    _insert_source_header_lines as _insert_source_header_lines,
    read_header_from_active_genome_index as read_header_from_active_genome_index,
    _mark_active_genome_index_build_completed as _mark_active_genome_index_build_completed,
    _upsert_metadata as _upsert_metadata,
    _ROW_CHROM as _ROW_CHROM,
    _ROW_POS as _ROW_POS,
    _ROW_END as _ROW_END,
    _ROW_SAMPLE_INDEX as _ROW_SAMPLE_INDEX,
    _ROW_IS_VARIANT as _ROW_IS_VARIANT,
    _ROW_FILTER as _ROW_FILTER,
    _ROW_GENOTYPE as _ROW_GENOTYPE,
    _ROW_DEPTH as _ROW_DEPTH,
    _ROW_GQ as _ROW_GQ,
    _reference_gq_tier as _reference_gq_tier,
    _ReferenceRunCoalescer as _ReferenceRunCoalescer,
    _min_optional as _min_optional,
    _record_row as _record_row,
    _sample_metrics as _sample_metrics,
    _info_end_and_genes as _info_end_and_genes,
    _split_gene_values as _split_gene_values,
    _unique_gene_values as _unique_gene_values,
    _record_is_variant as _record_is_variant,
    _insert_record_batch as _insert_record_batch,
    _insert_stat_rows as _insert_stat_rows,
    _rows_as_dicts as _rows_as_dicts,
    _sort_bins as _sort_bins,
    _chrom_sort as _chrom_sort,
)
from ._agi_readiness import (
    ActiveGenomeIndexSchemaTooNew as ActiveGenomeIndexSchemaTooNew,
    active_genome_index_summary as active_genome_index_summary,
    active_genome_index_readiness as active_genome_index_readiness,
    ensure_active_genome_index_complete as ensure_active_genome_index_complete,
    preflight as preflight,
    failure_summary as failure_summary,
    _active_genome_index_readiness_from_connection as _active_genome_index_readiness_from_connection,
    _public_active_genome_index_readiness as _public_active_genome_index_readiness,
    AGI_SCHEMA_CURRENT as AGI_SCHEMA_CURRENT,
    AGI_SCHEMA_NEEDS_REPARSE as AGI_SCHEMA_NEEDS_REPARSE,
    AGI_SCHEMA_TOO_NEW as AGI_SCHEMA_TOO_NEW,
    ActiveGenomeIndexNeedsReparse as ActiveGenomeIndexNeedsReparse,
    ActiveGenomeIndexIncomplete as ActiveGenomeIndexIncomplete,
    canonical_source_for_active_genome_index as canonical_source_for_active_genome_index,
    check_agi_schema_compatibility as check_agi_schema_compatibility,
)
from ._agi_query import (
    query_rsid as query_rsid,
    query_rsid_filtered as query_rsid_filtered,
    query_variant as query_variant,
    query_region as query_region,
    coverage_query as coverage_query,
    _query_offsets as _query_offsets,
    _query_point_region as _query_point_region,
    _point_spanning_offset_rows as _point_spanning_offset_rows,
    _point_spanning_offset_rows_from_spans as _point_spanning_offset_rows_from_spans,
    _point_spanning_offset_rows_from_records as _point_spanning_offset_rows_from_records,
    _offset_rows as _offset_rows,
    _execute_offset_query as _execute_offset_query,
    _dedupe_offset_rows as _dedupe_offset_rows,
    _records_from_active_genome_index_offsets as _records_from_active_genome_index_offsets,
    _index_record_to_dict as _index_record_to_dict,
    _row_has_key as _row_has_key,
    _json_list as _json_list,
    _row_sample_index as _row_sample_index,
    _merge_segments as _merge_segments,
)
from .reader import (
    ActiveGenomeIndexNeed as ActiveGenomeIndexNeed,
    ActiveGenomeIndexReader as ActiveGenomeIndexReader,
    open_reader as open_reader,
)
from ._agi_build import (
    create_active_genome_index as create_active_genome_index,
    append_reference_pass as append_reference_pass,
    _cached_active_genome_index_if_usable as _cached_active_genome_index_if_usable,
    _cached_record_limit_satisfies_request as _cached_record_limit_satisfies_request,
    _create_active_genome_index_parallel as _create_active_genome_index_parallel,
    _build_active_genome_index_shard as _build_active_genome_index_shard,
    _populate_records_from_byte_range as _populate_records_from_byte_range,
    _merge_active_genome_index_shards as _merge_active_genome_index_shards,
    _resolved_parallel_workers as _resolved_parallel_workers,
    _bgzip_indexed as _bgzip_indexed,
    _populate_records as _populate_records,
)

__all__ = [
    'SCHEMA_VERSION',
    'ACTIVE_GENOME_INDEX_BUILD_STATUS_IN_PROGRESS',
    'ACTIVE_GENOME_INDEX_BUILD_STATUS_COMPLETED',
    'REQUIRED_QUERY_OBJECTS',
    'ActiveGenomeIndexSchemaTooNew',
    'ActiveGenomeIndexStats',
    'default_active_genome_index_path',
    'connect',
    'connect_existing',
    'create_active_genome_index',
    'append_reference_pass',
    'active_genome_index_summary',
    'active_genome_index_readiness',
    'ensure_active_genome_index_complete',
    'query_rsid',
    'query_rsid_filtered',
    'query_variant',
    'query_region',
    'coverage_query',
    'preflight',
    'failure_summary',
    'AGI_SCHEMA_CURRENT',
    'AGI_SCHEMA_NEEDS_REPARSE',
    'AGI_SCHEMA_TOO_NEW',
    'ActiveGenomeIndexNeedsReparse',
    'canonical_source_for_active_genome_index',
    'check_agi_schema_compatibility',
    'read_header_from_active_genome_index',
    'ActiveGenomeIndexNeed',
    'ActiveGenomeIndexReader',
    'open_reader',
]
